[package]
name = "chip_wokwiscope"
version = "0.1.0"
edition = "2021"

[dependencies]
wokwi_chip_ll = "0.1"
minreq = "2.12.0"
zune-core = "0.4.12"
zune-jpeg = "0.4.13"

[lib]
crate-type = ["cdylib"]

[profile.release]
lto = true
opt-level = 's'
